ADAS_LEVEL_SAFE = 0
ADAS_LEVEL_INFO = 1
ADAS_LEVEL_ATTENTION = 2
ADAS_LEVEL_WARNING = 3
ADAS_LEVEL_EMERGENCY = 4

DMS_LEVEL_NORMAL = 0
DMS_LEVEL_ATTENTION = 1
DMS_LEVEL_WARNING = 2
DMS_LEVEL_DANGER = 3

IQA_LEVEL_NORMAL = 0
IQA_LEVEL_MINOR = 1
IQA_LEVEL_WARNING = 2
IQA_LEVEL_DANGER = 3

FUSION_LEVEL_SAFE = 0
FUSION_LEVEL_INFO = 1
FUSION_LEVEL_ATTENTION = 2
FUSION_LEVEL_WARNING = 3
FUSION_LEVEL_EMERGENCY = 4

SOURCE_ADAS = "ADAS"
SOURCE_DMS = "DMS"
SOURCE_IQA = "IQA"
SOURCE_FUSION = "FUSION"

EVENT_CAMERA_NORMAL = "CAMERA_NORMAL"
EVENT_CAMERA_SOILING = "CAMERA_SOILING"
EVENT_PERCEPTION_DEGRADED = "PERCEPTION_DEGRADED"
EVENT_IQA_INVALID = "IQA_INVALID"
EVENT_SENSOR_INVALID = "SENSOR_INVALID"
EVENT_SAFE = "SAFE"
