#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

import cv2
import numpy as np


CAMERAS = ["CAM_FRONT_LEFT", "CAM_FRONT", "CAM_FRONT_RIGHT", "CAM_BACK_LEFT", "CAM_BACK", "CAM_BACK_RIGHT"]
LEVEL_TEXT = ["SAFE", "INFO", "ATTENTION", "WARNING", "EMERGENCY"]


def read_jsonl(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def color(level: int) -> tuple[int, int, int]:
    return [(72, 190, 90), (80, 220, 220), (0, 188, 255), (0, 112, 255), (0, 0, 235)][max(0, min(4, level))]


def text(img, value, xy, scale=0.58, c=(235, 238, 242), thick=1):
    cv2.putText(img, str(value), xy, cv2.FONT_HERSHEY_SIMPLEX, scale, c, thick, cv2.LINE_AA)


def panel(img, xyxy, fill=(18, 22, 30), border=(55, 62, 74), thickness=1):
    x1, y1, x2, y2 = xyxy
    cv2.rectangle(img, (x1, y1), (x2, y2), fill, -1)
    cv2.rectangle(img, (x1, y1), (x2, y2), border, thickness)


def draw_cover(width, height, scene_name, source_label):
    canvas = np.zeros((height, width, 3), np.uint8)
    canvas[:] = (12, 15, 22)
    text(canvas, "Multi-source Perception Risk Fusion Demo", (120, 360), 1.45, (245, 248, 252), 3)
    text(canvas, "nuScenes Visual Replay + ADAS/TTC + DMS + IQA + Arbitration", (120, 435), 0.82, (170, 190, 215), 2)
    text(canvas, f"Scene: {scene_name}", (120, 515), 0.75, (120, 220, 255), 2)
    text(canvas, f"ADAS/TTC: {source_label} | IQA from custom test dataset", (120, 610), 0.68, (210, 215, 222), 1)
    return canvas


def draw_end(width, height, source_label):
    canvas = np.zeros((height, width, 3), np.uint8)
    canvas[:] = (12, 15, 22)
    text(canvas, "Demo Summary", (120, 285), 1.3, (245, 248, 252), 3)
    lines = [
        f"- ADAS/TTC generated from {source_label}",
        "- DMS generated from scripted timeline",
        "- IQA tested on custom soiling dataset",
        "- Fusion result generated by arbitration module",
    ]
    for i, line in enumerate(lines):
        text(canvas, line, (150, 380 + i * 58), 0.82, (210, 218, 230), 2)
    return canvas


def draw_camera_grid(canvas, scene_dir, frame, iqa):
    tile_w, tile_h = 385, 205
    x0, y0 = 30, 90
    for idx, cam in enumerate(CAMERAS):
        row, col = divmod(idx, 3)
        x = x0 + col * (tile_w + 14)
        y = y0 + row * (tile_h + 14)
        img_path = scene_dir / "demo_cache" / frame["camera_images"].get(cam, "")
        img = cv2.imread(str(img_path))
        if img is None:
            img = np.zeros((tile_h, tile_w, 3), np.uint8)
        img = cv2.resize(img, (tile_w, tile_h))
        canvas[y:y + tile_h, x:x + tile_w] = img
        soiled = cam in iqa.get("soiled_cameras", [])
        border = (0, 210, 255) if soiled else (80, 88, 100)
        cv2.rectangle(canvas, (x, y), (x + tile_w, y + tile_h), border, 3 if soiled else 1)
        text(canvas, cam, (x + 12, y + 28), 0.55, (255, 255, 255), 2)
        state = "SOILING" if soiled else "NORMAL"
        text(canvas, f"IQA {state}", (x + 12, y + tile_h - 14), 0.5, border, 2)
    text(canvas, "IQA status from custom test dataset", (30, 555), 0.5, (180, 190, 205), 1)


def draw_bev(canvas, objects, adas):
    x0, y0, w, h = 30, 585, 1183, 355
    panel(canvas, (x0, y0, x0 + w, y0 + h), (19, 24, 31), (62, 70, 82), 1)
    text(canvas, "BEV FSD-style View", (x0 + 18, y0 + 34), 0.7, (235, 238, 242), 2)
    origin = (x0 + w // 2, y0 + h - 42)
    scale = 6.0
    for meter in [10, 20, 30, 50]:
        yy = int(origin[1] - meter * scale)
        cv2.line(canvas, (x0 + 25, yy), (x0 + w - 25, yy), (50, 58, 68), 1)
        text(canvas, f"{meter}m", (x0 + 35, yy - 5), 0.42, (140, 150, 160), 1)
    for lane_y in [-3.5, 0, 3.5]:
        px = int(origin[0] - lane_y * scale)
        cv2.line(canvas, (px, y0 + 70), (px, y0 + h - 20), (66, 72, 82), 1, cv2.LINE_AA)
    cv2.rectangle(canvas, (origin[0] - 16, origin[1] - 28), (origin[0] + 16, origin[1] + 28), (220, 220, 220), -1)
    target = adas.get("target_object_id")
    for obj in objects.get("objects", []):
        x, y = float(obj.get("x", 0)), float(obj.get("y", 0))
        if x < -10 or x > 50 or abs(y) > 25:
            continue
        px = int(origin[0] - y * scale)
        py = int(origin[1] - x * scale)
        risk = obj.get("object_id") == target or obj.get("is_front_risk")
        c = color(int(obj.get("risk_level", 0))) if risk else (110, 155, 210)
        if obj.get("class_name") == "pedestrian":
            cv2.circle(canvas, (px, py), 6, c, -1)
        else:
            cv2.rectangle(canvas, (px - 9, py - 14), (px + 9, py + 14), c, 2 if risk else 1)
        if risk:
            cv2.circle(canvas, (px, py), 22, c, 2)
            text(canvas, f"RISK {obj.get('distance', 0):.1f}m", (px + 14, py - 10), 0.42, c, 1)


def draw_risk_panel(canvas, adas, dms, iqa, fusion):
    x0, y0, w, h = 1240, 90, 640, 850
    level = int(fusion["unified_risk_level"])
    panel(canvas, (x0, y0, x0 + w, y0 + h), (16, 20, 28), color(level), 4)
    text(canvas, f"FUSION LEVEL {level}", (x0 + 28, y0 + 58), 1.0, color(level), 3)
    text(canvas, LEVEL_TEXT[level], (x0 + 28, y0 + 106), 0.78, (240, 245, 250), 2)
    lines = [
        ("Primary", fusion["primary_event"]),
        ("ADAS", f"L{adas['adas_level']} {adas['event_type']}"),
        ("DMS", f"L{dms['danger_level']} {dms['event_type']}"),
        ("IQA", f"L{iqa['iqa_level']} {iqa.get('quality_state', '')}"),
        ("Soiled", ",".join(iqa.get("soiled_cameras", [])) or "none"),
        ("Perception", "DEGRADED" if fusion["source_status"].get("perception_degraded") else "OK"),
    ]
    y = y0 + 170
    for k, v in lines:
        text(canvas, k, (x0 + 30, y), 0.55, (150, 165, 185), 1)
        text(canvas, str(v)[:42], (x0 + 160, y), 0.62, (235, 238, 242), 2)
        y += 55
    text(canvas, "Triggered Events", (x0 + 30, y + 20), 0.62, (180, 200, 225), 2)
    for i, event in enumerate(fusion.get("triggered_events", [])[:5]):
        text(canvas, f"[{event['source']}] {event['event_type']}"[:44], (x0 + 30, y + 62 + i * 38), 0.52, (228, 232, 238), 1)
    if iqa.get("source_image"):
        thumb = cv2.imread(str(iqa["source_image"]))
        if thumb is not None:
            thumb = cv2.resize(thumb, (180, 100))
            canvas[y0 + h - 145:y0 + h - 45, x0 + 30:x0 + 210] = thumb
            text(canvas, "IQA Test Image", (x0 + 230, y0 + h - 96), 0.55, (210, 220, 235), 1)


def draw_timeline(canvas, adas_rows, dms_rows, iqa_rows, fusion_rows, idx):
    x0, y0, w = 30, 980, 1850
    cv2.line(canvas, (x0, y0), (x0 + w, y0), (88, 96, 110), 2)
    total = max(len(fusion_rows) - 1, 1)
    for rows, name, off, c in [(adas_rows, "ADAS", -22, (0, 190, 255)), (dms_rows, "DMS", 0, (255, 170, 70)), (iqa_rows, "IQA", 22, (0, 220, 255)), (fusion_rows, "L4", 44, (0, 0, 240))]:
        prev = -1
        for j, row in enumerate(rows):
            level = int(row.get("adas_level", row.get("danger_level", row.get("iqa_level", row.get("unified_risk_level", 0)))))
            if level > prev and level > 0:
                px = x0 + int(j / total * w)
                cv2.circle(canvas, (px, y0 + off), 5, c, -1)
                if level >= 3 or name == "L4":
                    text(canvas, name, (px + 6, y0 + off + 4), 0.35, c, 1)
            prev = level
    cur = x0 + int(idx / total * w)
    cv2.line(canvas, (cur, y0 - 42), (cur, y0 + 58), (245, 248, 252), 2)


def event_summary(adas, dms, iqa, fusion):
    events = []
    for rows, key, label in [(adas, "adas_level", "ADAS"), (dms, "danger_level", "DMS"), (iqa, "iqa_level", "IQA"), (fusion, "unified_risk_level", "Fusion")]:
        prev = 0
        for row in rows:
            level = int(row.get(key, 0))
            if level > prev and level >= 2:
                events.append(f"Frame {row['frame_index']:03d}: {label} rises to Level {level}")
            prev = level
    return events[:12]


def write_readme(scene_dir, out, width, height, fps, events, source_label):
    (scene_dir / "README_final_demo.md").write_text(
        "# Final Demo\n\n"
        f"## Flow\n\nnuScenes visual replay -> {source_label} ADAS/TTC inputs -> scripted DMS -> custom IQA test result -> arbitration -> FSD-style rendering.\n\n"
        "## Video\n\n"
        f"- Output: `{out}`\n- Resolution: {width}x{height}\n- FPS: {fps}\n- Includes: cover, six camera views, BEV, risk panel, event timeline, ending summary.\n\n"
        "## Key Events\n\n" + "\n".join(f"- {e}" for e in events) + "\n\n"
        f"## Boundaries\n\nADAS/TTC source: {source_label}. DMS uses a scripted timeline because nuScenes has no cabin camera. IQA comes from the custom normal/soiling test dataset, not nuScenes images.\n",
        encoding="utf-8",
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--scene-dir", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--width", type=int, default=1920)
    parser.add_argument("--height", type=int, default=1080)
    parser.add_argument("--fps", type=int, default=10)
    parser.add_argument("--adas-objects")
    parser.add_argument("--adas-status")
    parser.add_argument("--iqa-status")
    parser.add_argument("--fusion-status")
    parser.add_argument("--source-label", default="nuScenes GT boxes")
    args = parser.parse_args()
    scene_dir = Path(args.scene_dir)
    frames = read_jsonl(scene_dir / "demo_cache/frames.jsonl")
    objects = read_jsonl(Path(args.adas_objects) if args.adas_objects else scene_dir / "adas_objects.jsonl")
    adas = read_jsonl(Path(args.adas_status) if args.adas_status else scene_dir / "adas_status.jsonl")
    dms = read_jsonl(scene_dir / "dms_status.jsonl")
    iqa_path = Path(args.iqa_status) if args.iqa_status else scene_dir / "iqa_status_from_test.jsonl"
    iqa = read_jsonl(iqa_path if iqa_path.exists() else scene_dir / "iqa_status.jsonl")
    fusion = read_jsonl(Path(args.fusion_status) if args.fusion_status else scene_dir / "fusion_status.jsonl")
    meta = json.load((scene_dir / "demo_cache/meta.json").open())
    frames_dir = scene_dir / "final_frames"
    if frames_dir.exists():
        shutil.rmtree(frames_dir)
    frames_dir.mkdir(parents=True)
    rendered = []
    cover = draw_cover(args.width, args.height, meta.get("scene_name", "unknown"), args.source_label)
    end = draw_end(args.width, args.height, args.source_label)
    for _ in range(args.fps):
        rendered.append(cover)
    for idx, pack in enumerate(zip(frames, objects, adas, dms, iqa, fusion, strict=True)):
        frame, obj, adas_row, dms_row, iqa_row, fusion_row = pack
        canvas = np.zeros((args.height, args.width, 3), np.uint8)
        canvas[:] = (10, 13, 19)
        text(canvas, "AutoDriveLab Multi-source Risk Fusion", (30, 46), 0.85, (245, 248, 252), 2)
        text(canvas, f"{meta.get('scene_name')} | Frame {idx + 1:03d}/{len(frames):03d} | Fusion L{fusion_row['unified_risk_level']}", (770, 46), 0.62, color(int(fusion_row["unified_risk_level"])), 2)
        draw_camera_grid(canvas, scene_dir, frame, iqa_row)
        draw_bev(canvas, obj, adas_row)
        draw_risk_panel(canvas, adas_row, dms_row, iqa_row, fusion_row)
        draw_timeline(canvas, adas, dms, iqa, fusion, idx)
        rendered.append(canvas)
    for _ in range(args.fps):
        rendered.append(end)
    for i, image in enumerate(rendered):
        cv2.imwrite(str(frames_dir / f"{i:06d}.jpg"), image)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["ffmpeg", "-y", "-framerate", str(args.fps), "-i", str(frames_dir / "%06d.jpg"), "-c:v", "libx264", "-pix_fmt", "yuv420p", str(out)]
    try:
        subprocess.run(cmd, check=True)
    except Exception:
        writer = cv2.VideoWriter(str(out), cv2.VideoWriter_fourcc(*"mp4v"), args.fps, (args.width, args.height))
        for image in rendered:
            writer.write(image)
        writer.release()
    events = event_summary(adas, dms, iqa, fusion)
    write_readme(scene_dir, out, args.width, args.height, args.fps, events, args.source_label)
    print(f"Final demo: {out}")
    print(f"Frames: {frames_dir}")
    print(f"Key events: {len(events)}")


if __name__ == "__main__":
    main()
